version: '3.5'

volumes:
  db-data:

services:
  db:
    image: couchdb:3.1.1
    restart: always
    container_name: db
    networks:
      my-network:
    volumes:
      - db-data:/opt/couchdb/data
      - ./config/couch.ini:/opt/couchdb/etc/local.d/custom.ini
  backend:
    image: python:3.9.1-alpine3.12
    restart: always
    container_name: backend
    networks:
      my-network:
    ports:
      - 8080:5000
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python main.py"
    volumes:
      - db-data:/opt/couchdb/data
      - ./src:/app/
      - ./config/couch.ini:/var/lib/app/couch.ini

networks:
  my-network:
    driver: "bridge"
    name: "my-network"
